language: bash

services: docker

env: 
  - REPO=andrewmclagan/aphex

before_script:
  - export REPO_TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_TAG ; fi`   
  - export REPO_IMAGE="${REPO}:${REPO_TAG}"  
  - docker pull "$REPO" # For faster builds

script:
  - echo "${REPO_IMAGE}"
  - docker build -t "$REPO_IMAGE" .
  - docker images 

after_success:
  - echo "${REPO_IMAGE}"  
  - echo "$DOCKER_USER" "$DOCKER_PASS"
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS";
  - docker push "$REPO_IMAGE"